markdown: rdiscount
pygments: true
permalink: /:year/:month/:title/
auto: true
rdiscount:
  extensions: [smart]
  
# local configuration
# url: http://localhost/websites/jekyll/petals/
# url: http://petals.ow2.org/petals-community
server_port: 4444